name: StatsUI
version: 1.0.0
main: DerCommander610\StatsUI\Main
author: DerCommander610
api: 4.1.3
soft-depend: 
- FormAPI

commands:
  stats:
    description: "See other Players Stats!"
    permission: stats.ui.cmd
permissions:
  stats.ui.cmd:
    default: true
